language: python
sudo: false
python:
  - 2.6
  - 2.7
  - 3.0
  - 3.1
  - 3.2
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - 3.8-dev
  - pypy2.7
  - pypy3.5
  - pypy3.6
os:
  - linux
  - osx
services:
  - redis-server
install:
  - pip install -r requirements.txt
  - pip install pytest
script:
  - pytest -v tests