language: python
sudo: false
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - pypy3.5
services:
  - redis-server
before_install:
  - pip install -r requirements.txt
  - if [ "$TRAVIS_PYTHON_VERSION" = "2.7" ] || [ "$TRAVIS_PYTHON_VERSION" = "3.7" ]; then pip install pytest pytest-flake8 pytest-cov codecov; else pip install pytest; fi
script:
  - if [ "$TRAVIS_PYTHON_VERSION" = "2.7" ] || [ "$TRAVIS_PYTHON_VERSION" = "3.7" ]; then pytest -v --cov=delayed --cov-report term-missing -x tests; else pytest -v -x tests; fi
after_success:
  - if [ "$TRAVIS_PYTHON_VERSION" = "2.7" ] || [ "$TRAVIS_PYTHON_VERSION" = "3.7" ]; then codecov; fi