language: python
sudo: false
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - pypy3.5
services:
  - redis-server
install:
  - pip install -r requirements.txt
  - pip install pytest pytest-cov codecov
script:
  - pytest -v --cov=delayed --cov-report term-missing -x tests
after_success:
  - codecov