language: python
sudo: false
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - pypy
  - pypy3
services:
  - redis-server
before_install:
  - pip install -r requirements.txt
  - if [ "$TRAVIS_PYTHON_VERSION" = "2.7" ] || [ "$TRAVIS_PYTHON_VERSION" = "3.8" ]; then pip install pytest pytest-cov codecov; else pip install pytest; fi
script:
  - if [ "$TRAVIS_PYTHON_VERSION" = "2.7" ] || [ "$TRAVIS_PYTHON_VERSION" = "3.8" ]; then pytest -v --cov=delayed --cov-report term-missing -x tests; else pytest -v -x tests; fi
after_success:
  - if [ "$TRAVIS_PYTHON_VERSION" = "2.7" ] || [ "$TRAVIS_PYTHON_VERSION" = "3.8" ]; then codecov; fi
